In [37]:
import numpy as np

In [38]:
print(np.__version__)

1.23.3


In [31]:
l = [ 1, 2, 3, 4, 5, 6, 7, 8, 9]
type(l)

list

In [39]:
a = np.array(l)
type(a)

numpy.ndarray

In [44]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [41]:
b.shape

(3,)

In [50]:
d = np.array([[1,2,3,10],[4,5,6,10],[7,8,9,10]])
d

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 10]])

In [51]:
d.shape

(3, 4)

In [52]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a[0:4]

array([1, 2, 3, 4])

In [56]:
d

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10],
       [ 7,  8,  9, 10]])

In [63]:
d[0:2, 0:6]

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10]])